# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.firstLabelGoodMorning = QtWidgets.QLabel(self.centralwidget)
        self.firstLabelGoodMorning.setGeometry(QtCore.QRect(40, 10, 271, 321))
        self.firstLabelGoodMorning.setText("")
        self.firstLabelGoodMorning.setPixmap(QtGui.QPixmap("../../../../../Downloads/IMG_20211220_213238.jpg"))
        self.firstLabelGoodMorning.setScaledContents(True)
        self.firstLabelGoodMorning.setObjectName("firstLabelGoodMorning")
        self.ClickmeButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClickmeButton.setGeometry(QtCore.QRect(510, 100, 88, 34))
        self.ClickmeButton.setObjectName("ClickmeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 30))
        self.menubar.setObjectName("menubar")
        self.menuLoad_Sequence = QtWidgets.QMenu(self.menubar)
        self.menuLoad_Sequence.setObjectName("menuLoad_Sequence")
        self.menuSave_Analysis = QtWidgets.QMenu(self.menubar)
        self.menuSave_Analysis.setObjectName("menuSave_Analysis")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuLoad_Sequence.menuAction())
        self.menubar.addAction(self.menuSave_Analysis.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ClickmeButton.setText(_translate("MainWindow", "Click me!"))
        self.menuLoad_Sequence.setTitle(_translate("MainWindow", "Load Sequence"))
        self.menuSave_Analysis.setTitle(_translate("MainWindow", "Save Analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
